### ISSUE TITLE
#1 ローカル開発環境の作成を行う

### ISSUE THREAD

**Issue by Mitsuru53** [officeashley/vizzzy#1]
## TODO

- [x] Ruby on Rails(バックエンド)とNuxt.js(フロント)の初期化を行う
※Ruby on Railsはapiモードで初期化する。
参考: [Ruby on Railsをapiモードでセットアップする方法](http://railman.net/railsguides/5.0/api_app.html#%E3%82%A2%E3%83%97%E3%83%AA%E3%82%B1%E3%83%BC%E3%82%B7%E3%83%A7%E3%83%B3%E3%82%92%E6%96%B0%E8%A6%8F%E4%BD%9C%E6%88%90%E3%81%99%E3%82%8B)

参考 [Nuxtのセットアップ方法](https://webrandum.net/nuxt-setup/)
※TypeScriptはon、UIフレームワークはElementを選択してください

上記はDockerなしで対応していただいて大丈夫です

- [x] Ruby on Rails、Nuxt.js、mysqlをDockerで立ち上がるようにする

[Dockerとは](https://knowledge.sakura.ad.jp/13265/)
Dockerを使うことで環境構築を容易になります。
これにより私がレビューをしやすくなり、環境差異による動作が違うみたいなことが起きにくくなります

[docker compose](https://o2mamiblog.com/docker-beginner-2/#:~:text=Docker%20Compose%E3%81%A8%E3%81%AF%E8%A4%87%E6%95%B0,Docker%20Compose%E3%82%92%E4%BD%BF%E3%81%84%E3%81%BE%E3%81%99%EF%BC%81)を利用することで複数コンテナを操作しやすくなります

[Nuxt、Rails、mysqlをDockerで動かす方法](https://qiita.com/yassun-youtube/items/1dfed3115135929f877b)

- [x] Nuxt.jsをSSRモードに設定されていること(OGP対応のため)

[SSRとは](https://qiita.com/a_ya_ka/items/f1fbd3b324a84f517e85)

- [ ] フロントとバックエンド間で通信ができること
※適当なAPIをバックエンドに定義し、フロントからそのAPIを呼び出せるようになっていればOK

参考: [NuxtからRailsへリクエストを投げる方法](https://blog.cloud-acct.com/posts/spa-nuxt-firstapi/)

**Comment by officeashley** [comment]
ごめんなさい。タスクを確認したのですが
どのように取り組んでいいのか？わからない場合は何を参照すればいいのか等全く分からない状況なのですが。
こちら全くの初心者というご認識でお願いできませんでしょうか？？

**Comment by officeashley** [comment]
レファレンス先等のご教示等いただけるとありがたいです。この感じだときついです。

**Comment by officeashley** [comment]
大変申し訳ございません。もしお互い認識があっておらず私のレベルだと手に余るということでしたら、今回の依頼はキャンセルでも結構ですので、その旨ご教示くださいませ。

**Comment by Mitsuru53** [comment]
@officeashley 
失礼しました 🙇 
各タスクにそれぞれ参考リンクや補足コメントを付与しました
これで着手できますでしょうか？もし手を動かす上で他わからない点などあればお気軽にご相談ください

**Comment by officeashley** [comment]
参考 [Nuxtのセットアップ方法](https://webrandum.net/nuxt-setup/)
※TypeScriptはon、UIフレームワークはElementを選択してください。とあるのですが、添付のような状態になり、TypeScriptはon、UIフレームワークはElement等の設定を行うことができません。インストールしなおしたほうがいいでしょうか？
![image](https://user-images.githubusercontent.com/119099240/204127642-9818e3db-06dd-4fbd-82dc-16a8acca32e6.png)

**Comment by Mitsuru53** [comment]
@officeashley 

スクショを見ると、 create-nuxt -appとなっています。nuxtと-appの間に不要なスペースがあるように見えます。

`npx create-nuxt-app プロジェクト名`  で試していただけますか？

**Comment by officeashley** [comment]
![image](https://user-images.githubusercontent.com/119099240/204133661-314c1f6f-fc6a-4cab-9810-6d38c359cdde.png)
このような状況変わらずです。（一度アンインストール、再度ダウンロードし直しての結果です。）TypeScriptはon、UIフレームワークはElement等の設定を行うことができません。

**Comment by Mitsuru53** [comment]
先のコメントにて`npx create-nuxt-app プロジェクト名`と記載したのですが、npx crerate-nuxt-appとだけ打っていてプロジェクト名が記載されていないように見えます
適当なプロジェクト名(アプリの名前とかなんでもいいです)を入れて打ち直してみてください

**Comment by officeashley** [comment]
![image](https://user-images.githubusercontent.com/119099240/204134024-816a708a-c5c9-4255-8cf8-41fde68c7df7.png)
こちらで入れなおしたのですが、やはり画像の通りです。

**Comment by Mitsuru53** [comment]
なるほど。npxとnpmのバージョンを確認したいです
npx -vとnpm -vそれぞれを実行した結果のスクショをいただけますか？

**Comment by officeashley** [comment]
![image](https://user-images.githubusercontent.com/119099240/204134568-aecfa1c6-1153-4fa7-99c5-bd458dd491eb.png)
こちらになります。よろしくお願いいたします。

**Comment by Mitsuru53** [comment]
ありがとうございます！npmもnpxも問題なくinstallされていますね。
yarnで試してみましょうか

```
npm i -g yarn
yarn create-nuxt-app プロジェクト名
```
でどうなるか確認していただけますか？

**Comment by Mitsuru53** [comment]
yarnとは
参考 https://qiita.com/akitaaa/items/c97ff951ca31298f3f24

**Comment by officeashley** [comment]
![image](https://user-images.githubusercontent.com/119099240/204135285-2e241516-49fe-4d46-8f7f-fe794a386e51.png)
このような状況ですが、なにが起こっているのかわかりません。

**Comment by Mitsuru53** [comment]
ありがとうございます
ちなみにカレントディレクトリはどこで、そのカレントディレクトリには何かファイルとかありますか？

**Comment by officeashley** [comment]
![image](https://user-images.githubusercontent.com/119099240/204137583-22a3d9d4-d936-497f-ab50-781989d3b758.png)
カレントディレクトリです。Couldn't find a package.json file in "C:\\Users\\user"　がないと書いてあるので、package.json fileをダウンロードして、このディレクトリに保存すればいいという感じでしょうか？とは言っても、ダウンロード方法を検索中ですがなかなかこれといったものが見つからず状態です。

**Comment by Mitsuru53** [comment]
ありがとうございます
package.jsonおよびpackage-lock.jsonがあるのですね。
これが邪魔をしている可能性があります。
なので適当なディレクトリを作成していただき、そのディレクトリで `npx create-nuxt-app プロジェクト名` をもう一度試していただけますか？

**Comment by officeashley** [comment]
![image](https://user-images.githubusercontent.com/119099240/204256057-d115ec03-d979-45ee-a3ed-297450f82c8c.png)
でィレクトリ変更、yarn にて添付の通り先に進むことはできました。ご確認ください。（Errorも出ていますので、ご確認下さいませ。）

**Comment by Mitsuru53** [comment]
@officeashley 
operation not permitted. mkdirとなっていますね。つまり権限エラーです。
mkdirする権限がないため失敗したと考えられます。
なので、管理者権限でコマンドを実行してみてください。

`windows 管理者権限 コマンド実行` などで検索してみて、どうしたら管理者権限でコマンドを打てるのか調べてみてください 👍

**Comment by officeashley** [comment]
![image](https://user-images.githubusercontent.com/119099240/204500480-98945c13-8a0f-45d3-b04e-2288b15e838b.png)
@Mitsuru53  スクショ通り、あドミン権限、何も入ってないディレクトリから　yarn create nuxt -app test　で打ちましたが又ハローワールドが出て先に進めなくなりました。如何すればよろしいでしょうか？
![image](https://user-images.githubusercontent.com/119099240/204501241-dc7c931c-87fa-46ef-8812-a6ba468160ce.png)

**Comment by Mitsuru53** [comment]
@officeashley 

実行されているコマンドですが、create-nuxt-appが正しいところ、nuxtやappの前のハイフンがないように見えます
(create nuxt appやcreate-nuxt appになっている)
create-nuxt-appと正しく打ってもうまくいかなかったでしょうか？

**Comment by officeashley** [comment]
![image](https://user-images.githubusercontent.com/119099240/204551156-019cf3d0-adb5-490d-9c68-6229bbb46d24.png)
はい上の物をそのままコピペでも画像の通りです。　ディレクトリはこのような感じです。
![image](https://user-images.githubusercontent.com/119099240/204551479-522f54f6-c4ca-488c-8c18-defddc2dd11b.png)

**Comment by Mitsuru53** [comment]
なるほど、ありがとうございます

```
yarn global add create-nuxt-app

create-nuxt-app プロジェクト名
```
を試していただけますでしょうか？

**Comment by officeashley** [comment]
![image](https://user-images.githubusercontent.com/119099240/204768441-71763108-0ee4-4884-8c82-64c0f9a1f730.png)
このような状態です。何が問題でしょうか？？

**Comment by officeashley** [comment]
Ruby on Rails、Nuxt.js、mysqlをDockerで立ち上がるようにするですが、Nuxt.jsでスタックしているので、省いて立ち上がるようにしても一先ず大丈夫ですか？

**Comment by Mitsuru53** [comment]
@officeashley 
コメントの通知が来たのですが、コメントが見当たらないのですが、削除などされたでしょうか？

**Comment by officeashley** [comment]
上記は解決しました。
前提の質問ですが、レファレンスビデオを見ていると、多くがmac マシーンを利用しているのですが、私は今、Windowsを使ってコレラのことをやっていますが、問題はないでしょうか？

又次のRuby on Rails、Nuxt.js、mysqlをDockerで立ち上がるようにするですが、docker hub からイメージを取得し, コンテナを動かすということを行ったつもりなのですが、画像の通りで大丈夫でしょうか？ご確認ください。
![image](https://user-images.githubusercontent.com/119099240/204816987-03b4fd20-9918-414c-87dd-c3d2daa4ee15.png)

**Comment by Mitsuru53** [comment]
@officeashley 
> 前提の質問ですが、レファレンスビデオを見ていると、多くがmac マシーンを利用しているのですが、私は今、Windowsを使ってコレラのことをやっていますが、問題はないでしょうか？

はい、windowsでも全く問題ありません。

> 又次のRuby on Rails、Nuxt.js、mysqlをDockerで立ち上がるようにするですが、docker hub からイメージを取得し, コンテナを動かすということを行ったつもりなのですが、画像の通りで大丈夫でしょうか？ご確認ください。

これは少し違いますね。NuxtとRailsに関してはそれぞれのディレクトリでDockerイメージは自作する必要があります。
NuxtはnodeをベースイメージにしたDockerfileを作成、RailsはRubyをベースイメージにしたDockerfileを作成。
mysqlはmysqlのベースイメージを取得すればいいのですが、日本語対応などしようとするとこちらもDockerfileを作成して対応する必要があります。
これらのDockerfileを束ねる(オーケストレーション)役割で、docker-compose.ymlを作成する必要があります
参考: [Nuxt、Rails、mysqlをDockerで動かす方法](https://qiita.com/yassun-youtube/items/1dfed3115135929f877b)

**Comment by officeashley** [comment]
本件、ギブアップです。どう調べてもどうしたらいいのかまったくわからないので、一つだけでもいいのでサンプルで教えてください。アドミンでコマンドプロントを開いており、ディレクトリは
C:\Users\akikoを指定しております。
![image](https://user-images.githubusercontent.com/119099240/205027455-5b3e2e7c-1ec2-4344-8b2a-139ed77766e5.png)

**Comment by Mitsuru53** [comment]
@officeashley 
承知しました。サンプル作成いたします。
サンプル作成のため、現状RailsとNuxtのセットアップはできていると思うので、それをGitHubに上げていただいてもよろしいでしょうか？

Dockerについてですが参考書を載せておきます。こちら私がメンターしているスクールでDockerの導入用に使っている教材です。ご多忙だと存じますが、ご興味あればお試しください。
[参考書](https://www.amazon.co.jp/%E5%9B%B3%E8%A7%A3%EF%BC%81-Docker%E3%81%AE%E3%83%84%E3%83%9C%E3%81%A8%E3%82%B3%E3%83%84%E3%81%8C%E3%82%BC%E3%83%83%E3%82%BF%E3%82%A4%E3%81%AB%E3%82%8F%E3%81%8B%E3%82%8B%E6%9C%AC-%E8%A7%92%E9%96%93%E5%AE%9F-ebook/dp/B0B4VCT87Q?__mk_ja_JP=%E3%82%AB%E3%82%BF%E3%82%AB%E3%83%8A&crid=NI04G8REBP2Y&keywords=docker&qid=1669907379&qu=eyJxc2MiOiI0Ljk5IiwicXNhIjoiNC4xOCIsInFzcCI6IjMuOTYifQ%3D%3D&sprefix=docke%2Caps%2C199&sr=8-23&linkCode=ll1&tag=exhikkii0e-22&linkId=d8113558457290fbc639668e086b4747&language=ja_JP&ref_=as_li_ss_tl)

**Comment by officeashley** [comment]
書籍購入したので、きたら読み始めてみます。ありがとうございます。

**Comment by Mitsuru53** [comment]
@officeashley 
私もその書籍手元にあるので、書籍でわからないこともお気軽にご質問ください
RailsとNuxtをGitHubに上げていただくことを併せてお願いいたします

**Comment by officeashley** [comment]
本件、全く分からなくて申し訳ないのですが、再確認です。NuxtとRailsに関してはそれぞれのディレクトリでDockerイメージは自作する必要があります。NuxtはnodeをベースイメージにしたDockerfileを作成、RailsはRubyをベースイメージにしたDockerfileを作成。とありますが、コマンドプロントを利用せず、Ruby on Rails、Nuxt.jsに関しては、docker hub からイメージを取得するやり方で問題ないということでしょうか？ご確認ください。

**Comment by Mitsuru53** [comment]
> NuxtとRailsに関してはそれぞれのディレクトリでDockerイメージは自作する必要があります。

はい、あってます！

> NuxtはnodeをベースイメージにしたDockerfileを作成、RailsはRubyをベースイメージにしたDockerfileを作成。とありますが、コマンドプロントを利用せず、Ruby on Rails、Nuxt.jsに関しては、docker hub からイメージを取得するやり方で問題ないということでしょうか？

こちらはコマンドプロンプトも使う可能性はありますね
まず完成形のイメージですが、testディレクトリ配下でコード管理すると想定した時、testディレクトリは以下のようになります

```
test/
┣ backend(Railsディレクトリ)
┃. ┣  Dockerfile
┃  ┣. 他のRailsのコード 
┣  front(Nuxtディレクトリ)
┃. ┣  Dockerfile
┃  ┣. 他のNuxtのコード 
┣  DB(mysqlディレクトリ)
┃. ┣  Dockerfile
┣ docker-compose.yml
```

それぞれのDockerfileとdocker-compose.ymlを作成してください、これはコマンドプロンプトの作業では無いです
それぞれのDockerfile内でdocker hubからどのイメージを使うか指定する形です
Dockerイメージの作成やコンテナの起動や停止はコマンドプロンプトでの作業になります

**Comment by officeashley** [comment]
- NuxtはnodeをベースイメージにしたDockerfileとdocker-compose.ymlを作成してくださいですが、やっていることがあっている確認をお願いします。
- こちらのフォルダーに”nuxtproject”のフォルダーを作成し、

![image](https://user-images.githubusercontent.com/119099240/205436273-e4c11864-b286-45c1-a7ba-fe7d5edbb349.png)

- テキストで二つのドキュメントを作成

![image](https://user-images.githubusercontent.com/119099240/205436314-072e5f97-5d23-49a9-9a9b-55fc99fa2440.png)

- docker-compose.yml　はこちらのように記述

![image](https://user-images.githubusercontent.com/119099240/205436352-d758d12e-23ce-47e7-b3ad-37e9c0cb043d.png)

- Dockerfile　はこちらのように記述しました。

![image](https://user-images.githubusercontent.com/119099240/205436382-b5e3a3ce-c145-4ae7-8833-8704b9526a23.png)

※やってることが合っているかご確認の程、宜しくお願いします。

**Comment by Mitsuru53** [comment]
@officeashley 
nuxtprojectの配下にDockerfileを作成するのは問題ありません
docker-compose.ymlはnuxtprojectと同じ階層に置きたいです。nuxtprojectと同じ階層にrailsのprojectも置く想定ですが、docker-compose.ymlがnuxtproject内にあると不便なためです。

Dockerおよびdocker-compose.ymlの記述が正しいかは、コンテナイメージを作成でき、そのイメージカラコンテナを起動できていれば正しくできています。以下がdocker composeを利用したイメージ作成とコンテナ起動コマンドになります。
```
docker compose build // イメージ作成
docker compose up // コンテナ起動
```

**Comment by officeashley** [comment]
![image](https://user-images.githubusercontent.com/119099240/205487248-3c0423ce-a22a-4f64-b41e-01d155b094d2.png)
げんざい、github に、rails をアップすることを添付の通り行ってのですが、エラーが出ております。
![image](https://user-images.githubusercontent.com/119099240/205487620-a4cb2115-215d-4af5-a124-b794942c1b70.png)
こんなエラーが出ました。

**Comment by officeashley** [comment]
![image](https://user-images.githubusercontent.com/119099240/205487768-9e53fff1-352e-4e73-9318-c3017109d051.png)
github 上ではこんな感じです。

**Comment by Mitsuru53** [comment]
@officeashley 
2枚目の画像に `fatal: protocol '[https' is not supported` と出ていますね。
リモートリポジトリのアドレスを登録の際に変な文字列が入ってしまっている可能性があります。
リモートリポジトリのアドレスを登録をやり直してみてください

**Comment by officeashley** [comment]
rails と　nuxt を　github にpush できました。次、Nuxt.jsをSSRモードに設定されていること(OGP対応のため)ですが、設定はコマンドプロンプトで行いますか？それともテキストを作成する形でしょうか？色々見ているのですが、いまいちわかりません。よろしくお願いします。

**Comment by officeashley** [comment]
> @officeashley nuxtprojectの配下にDockerfileを作成するのは問題ありません docker-compose.ymlはnuxtprojectと同じ階層に置きたいです。nuxtprojectと同じ階層にrailsのprojectも置く想定ですが、docker-compose.ymlがnuxtproject内にあると不便なためです。
> 
> Dockerおよびdocker-compose.ymlの記述が正しいかは、コンテナイメージを作成でき、そのイメージカラコンテナを起動できていれば正しくできています。以下がdocker composeを利用したイメージ作成とコンテナ起動コマンドになります。
> 
> ```
> docker compose build // イメージ作成
> docker compose up // コンテナ起動
> ```
rails, nuxt はそれぞれdockerfile とdocker-compose.ymlを自作したのですが、そのあとはコマンドプロンプトで、
docker compose build // イメージ作成
> docker compose up // コンテナ起動　を行う理解であってますか？現在docker desktop ではこんな状態です。

![image](https://user-images.githubusercontent.com/119099240/205635886-64050614-6b1e-4724-a39a-cda30add7ee9.png)

**Comment by Mitsuru53** [comment]
@officeashley 
> rails と　nuxt を　github にpush できました

こちらですがnuxtとrailsを別々のリポジトリとして管理するのではなく、先日私が[コメントで図示](https://github.com/officeashley/vizzzy/issues/1#issuecomment-1335199531)しました通り、一つのリポジトリとして管理したいです。
理由としてはリポジトリを分けてもできるのですが、リポジトリを分けるとdockerの設定の際に難易度の高いネットワーク設定
する必要があるので避けたいためです。
このリポジトリにrailsとnuxtをpushお願いいたします。

> rails, nuxt はそれぞれdockerfile とdocker-compose.ymlを自作したの

docker-compose.ymlは1つで大丈夫です
docker-compose.ymlがrailsとnuxtのDockerfileを参照して、railsとnuxtのコンテナを作成するようにします。

このリポジトリのトップディレクトリは
docker-compose.ymlとbackend(railsのコードがあるディレクトリ)とfront(nuxtのコードがあるディレクトリ)になります

> 次、Nuxt.jsをSSRモードに設定されていること(OGP対応のため)ですが、設定はコマンドプロンプトで行いますか？

こちらはコードで設定します。
Nuxt公式サイトにssrに設定する方法が記載されていますので、こちらをご参照下さい
[ssrの設定方法](https://nuxtjs.org/docs/configuration-glossary/configuration-ssr/)

**Comment by officeashley** [comment]
![image](https://user-images.githubusercontent.com/119099240/205900572-74da3389-60aa-4501-aef4-c10db3308844.png)
@Mitsuru53 testの下にrails, nuxt をGITHUBに置いたつもりですが、これであってますか？ご確認ください。

**Comment by Mitsuru53** [comment]
@officeashley 
確認しましたが、railsのコードもnuxtのコードもないように見えますね。。。
railsやnuxtのコードをgit addでcommit対象に含めましたでしょうか？

**Comment by Mitsuru53** [comment]
適当なディレクトリでrailsとnuxtを作成してみてください
railsとnuxtをセットアップするとデフォルトでそれぞれgit管理されています
まずそのgit管理を削除します
.gitディレクトリでgit管理されているので、それぞれのディレクトリでrm -r .gitを行うことでデフォルトのgit管理を削除できるはずです
次にrailsとnuxtディレクトリと同じ階層でgit initをし、git remoteを適当なリポジトリに設定することでrailsとnuxtを1つのリポジトリとして管理できるはずです
他、何かご不明点などあればお気軽にご相談ください

**Comment by officeashley** [comment]
> @officeashley 確認しましたが、railsのコードもnuxtのコードもないように見えますね。。。 railsやnuxtのコードをgit addでcommit対象に含めましたでしょうか？

railsのコードもnuxtのコードとは何のことを指しているのでしょうか？何か画像で参照できるものありますか？

**Comment by officeashley** [comment]
railsやnuxtのコードをgit addでcommit対象に含めましたでしょうか？とのことですが、add . ですべてをcommit対象にしました。

C:\Users\user\node_modules>git add .

C:\Users\user\node_modules>git add .

**Comment by officeashley** [comment]
現在、頭に戻っているのですが、Ruby on Rails(バックエンド)とNuxt.js(フロント)の初期化を行うということろで両方とも、
localhost:3000　  をgoogleクロームでサーバーがたちがるところまで確認すべきですか？と申しますのも、両方とも、これが出てしまいまして。 @Mitsuru53 
![image](https://user-images.githubusercontent.com/119099240/206181618-7575f14d-7a24-400d-95ee-3476c51fb391.png)

**Comment by officeashley** [comment]
> 適当なディレクトリでrailsとnuxtを作成してみてください railsとnuxtをセットアップするとデフォルトでそれぞれgit管理されています まずそのgit管理を削除します .gitディレクトリでgit管理されているので、それぞれのディレクトリでrm -r .gitを行うことでデフォルトのgit管理を削除できるはずです 次にrailsとnuxtディレクトリと同じ階層でgit initをし、git remoteを適当なリポジトリに設定することでrailsとnuxtを1つのリポジトリとして管理できるはずです 他、何かご不明点などあればお気軽にご相談ください

@Mitsuru53 最初がうまくダウンロードできてなかったので、やり直しまして今このような状態です。まずご確認いただけますでしょうか？新しいレポジトリーはnewtest にしております。
![image](https://user-images.githubusercontent.com/119099240/206191447-24bc2af0-6c27-459b-af8f-e919e27ac30f.png)

やはり、下記のことをやる必要がありますでしょうか？↓
ーーー
git管理を削除します
.gitディレクトリでgit管理されているので、それぞれのディレクトリでrm -r .gitを行うことでデフォルトのgit管理を削除できるはずです
次にrailsとnuxtディレクトリと同じ階層でgit initをし、git remoteを適当なリポジトリに設定することでrailsとnuxtを1つのリポジトリとして管理できるはずです
ーーー

**Comment by Mitsuru53** [comment]
@officeashley 

> Ruby on Rails(バックエンド)とNuxt.js(フロント)の初期化を行うということろで両方とも、
localhost:3000　 をgoogleクロームでサーバーがたちがるところまで確認すべきですか？と申しますのも、両方とも、これが出てしまいまして。 

RailsとNuxt両方とも立ち上げていますか？
両方とも3000portを使っているので、バッティングしてそのような画面が出ている可能性があります
rails sでサーバーを立ち上げているかと思いますが、 `rails s -p 3030` のような形でportを指定してサーバーを立ち上げることができます
これでNuxtを立ち上げ、Railsも立ち上げた時にそれぞれ画面表示がどうなるか見てみてほしいです

> まずご確認いただけますでしょうか？

確認いたしました。Rails関連のコードはpushできているようですが、Nuxtのコードがないように見えます

> やはり、下記のことをやる必要がありますでしょうか？↓

こちらしていただいた方が、docker設定の際に楽になるのでしていただきたいです
よろしくお願いいたします

**Comment by officeashley** [comment]
@Mitsuru53  おせわになっております。明日札幌に出張なので今夜はお休みします。次のVCの日時だけご教示いただければ幸いです。よろしくお願いします。

**Comment by Mitsuru53** [comment]
@officeashley 

> 明日札幌に出張なので今夜はお休みします。

承知しました。出張お疲れ様です。

> 次のVCの日時だけご教示いただければ幸いです。

例えば以下の日時はいかがでしょうか？もしご都合が合わない場合、いくつかご都合の良い日時をご教示いただけますと幸いです。よろしくお願い致します。
10日(土) 10:00 ~ 11:00
10日(土) 14:00 ~ 15:00
10日(土) 20:00 ~ 21:00

11日(日) 13:00 ~ 14:00
11日(日) 20:00 ~ 21:00

12日(月) 20:00 ~ 21:00

**Comment by officeashley** [comment]
@Mitsuru53 おせわになっております。１２日でお願いします。出張がタイトスケジュールにて作業ができませんでしてお返事が遅くなり申し訳ありませんでした。本日質問したいことなど考えておきます。VCのグーグルミートのリンクをお送りくださいませ。

**Comment by officeashley** [comment]
@Mitsuru53 rails はイメージの通りうまくいきました
![image](https://user-images.githubusercontent.com/119099240/206889546-673ead97-78ae-44a2-9e3f-e058c4a273a8.png)　rails

**Comment by officeashley** [comment]
> 適当なディレクトリでrailsとnuxtを作成してみてください railsとnuxtをセットアップするとデフォルトでそれぞれgit管理されています まずそのgit管理を削除します  とのことなのですがこちらがうまくいないというか対象のファイルが無いように思います。
rails:
![image](https://user-images.githubusercontent.com/119099240/206891681-5d009587-0a18-48f4-bda7-2aeb66db2619.png)
nuxt:
![image](https://user-images.githubusercontent.com/119099240/206891709-4c58b4a6-81bc-4475-ae02-1ab8ac2e5dd6.png)
VC の時にご指導いただけますでしょうか？よろしくお願いします。

**Comment by Mitsuru53** [comment]
@officeashley 
明日12日20~21時でよろしくお願いいたします。

> VC の時にご指導いただけますでしょうか？よろしくお願いします。

承知しました、ではVC繋いで一緒にやってみましょう

時間になりましたら、以下のリンクからよろしくお願いいたします。
https://meet.google.com/bdd-ubzg-owp

**Comment by officeashley** [comment]
質問事項：
ー機能リスト
ーnuxt 3000たちあがらない。
ーgit管理削除
ー Nuxt.jsをSSRモードに設定

**Comment by Mitsuru53** [comment]
Nuxtを動かすためにはコマンドプロンプトで以下を打つ必要がある
```
set NODE_OPTIONS=--openssl-legacy-provider
```

**Comment by officeashley** [comment]
ありがとうございました！！！引き続きよろしくお願いいたします。

**Comment by Mitsuru53** [comment]
@officeashley 
こちらこそありがとうございました！
今月末ぐらいにもしお時間ありましたら、今回のような形で、もう一度メンタータイム設けたいのですが、ご都合いかがでしょうか？
もし年末ご多忙でしたら、1ヶ月お休みの間のどこかでも大丈夫です 👍

**Comment by Mitsuru53** [comment]
導入本としてご利用ください。
[Ruby](https://amzn.to/3iWUnov)
[Git](https://amzn.to/3uGKDkL)
[Vue](https://amzn.to/3YeN1wC)

今後おすすめの参考書など必要であれば適宜ご連絡ください。
その都度、目的に応じた本をご紹介いたします

**Comment by officeashley** [comment]
もうしわけございません。出張づかれでダウンしており、明日以降で折り返しさせてください。

**Comment by Mitsuru53** [comment]
@officeashley 
お疲れ様です！
はい、落ち着いてからで大丈夫です 👍

**Comment by officeashley** [comment]
体を壊しておりました。
ありがとうございます。ではお言葉に甘えておねがいします。来週の19時以降できれば平日でどこでも結構です。決め打ちでご連絡くださいませ。

一件質問ですが、コマンドプロンプトは保存ができないのでしょうか？ｐｃがダウンしてしまい、前回教えてもらったコマンドを参照しながら、MySQLをセットアップしようと思っていたのに、できなくなって落ち込んでおります。💦

**Comment by Mitsuru53** [comment]
> 来週の19時以降できれば平日でどこでも結構です。決め打ちでご連絡くださいませ。

こちら、では23日(金) 20:30 ~ 21:30 でお願いいたします。

> 一件質問ですが、コマンドプロンプトは保存ができないのでしょうか？

windowsだとF7キーでコマンド履歴が見れるようですが、いかがでしょうか？
https://atmarkit.itmedia.co.jp/ait/articles/1809/27/news035.html

pcダウンしてしまうと履歴が吹っ飛んでしまっている可能性もありますね
もしコマンドであれなんだったけななどご不明点あればお気軽にご質問ください

**Comment by Mitsuru53** [comment]
@officeashley 
本日この後大丈夫でしょうか？
ご返信がなかったので、念の為の確認です
ご都合悪いなどあればお気軽にお申し付けください

**Comment by officeashley** [comment]
https://meet.google.com/qft-fvgd-oeh

申しわけございません。予定しておりました。上記にてお待ちしております。

**Comment by Mitsuru53** [comment]
@officeashley 
ご連絡&リンクありがとうございます！
では30分からよろしくお願いいたします

**Comment by officeashley** [comment]
@Mitsuru53 お世話になっております。明けましておめでとうございます。今年もよろしくお願いします。次のセッションは2月以降になりまして、それまでに機能リスト、環境設定を完了させてから次に移りたいと思っております。最終回のセッションで納品後のこの期間でも、質問を投げて構わないとおっしゃっていただいた記憶があるのですが、料金が発生していないので、こちらは私の記憶違いということでよろしかったでしょうか？

**Comment by Mitsuru53** [comment]
@officeashley 
あけましておめでとうございます！本年もよろしくお願いいたします。

> 最終回のセッションで納品後のこの期間でも、質問を投げて構わないとおっしゃっていただいた記憶があるのですが、料金が発生していないので、こちらは私の記憶違いということでよろしかったでしょうか？

はい、質問投げていただいて大丈夫ですよ！
サービス購入されてる場合は24時間以内にお返事対応するのですが、サービス購入していないこの期間は24時間以内に返答できない場合がありますがご了承ください。他のクライアント様(サービス購入されている方)を優先的に対応するためです。
とはいえ、なるはやで返信するようにはいたします！
